import uuid
from django.db import models
from django.core.validators import MinValueValidator
from apps.channels.models import Channel


class PostType(models.TextChoices):
    TEXT = "text", "Text"
    IMAGE = "image", "Image"
    VIDEO = "video", "Video"
    REEL = "reel", "Reel"
    CAROUSEL = "carousel", "Carousel"


class PostSource(models.TextChoices):
    """
    Where did this post come from?

    BOT     — sent directly to the bot by the channel owner
    CHANNEL — automatically synced from a linked Telegram channel
    MANUAL  — created via the web dashboard
    """
    BOT = "bot", "Bot"
    CHANNEL = "channel", "Channel Sync"
    MANUAL = "manual", "Manual"


class Post(models.Model):
    """
    Core content unit. One Post = one piece of content on the website.

    telegram_message_id is stored to:
    1. Deduplicate incoming webhook events (idempotency)
    2. Link back to the original Telegram message for deep-linking
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    channel = models.ForeignKey(
        Channel,
        on_delete=models.CASCADE,
        related_name="posts",
        db_index=True,
    )

    # --- Content ---
    type = models.CharField(
        max_length=16,
        choices=PostType.choices,
        default=PostType.TEXT,
        db_index=True,
    )
    title = models.CharField(max_length=256, blank=True)
    content = models.TextField(blank=True)

    # --- Media ---
    media_file = models.FileField(
        upload_to="posts/media/%Y/%m/%d/",
        blank=True,
        null=True,
        help_text="Primary media asset. Stored on S3 in production.",
    )
    thumbnail = models.ImageField(
        upload_to="posts/thumbnails/%Y/%m/%d/",
        blank=True,
        null=True,
        help_text="Auto-generated by Celery task for video/reel types.",
    )

    # --- Telegram metadata ---
    telegram_message_id = models.BigIntegerField(
        null=True,
        blank=True,
        db_index=True,
        help_text=(
            "Original Telegram message ID. "
            "Used for deduplication and deep-link back to source."
        ),
    )
    telegram_file_id = models.CharField(
        max_length=256,
        blank=True,
        help_text=(
            "Telegram's file_id for re-downloading media. "
            "Cheaper than storing the raw file URL."
        ),
    )

    # --- Engagement ---
    views_count = models.PositiveIntegerField(
        default=0,
        validators=[MinValueValidator(0)],
        help_text="Flushed from Redis counters by Celery batch task.",
    )

    # --- State ---
    source = models.CharField(
        max_length=16,
        choices=PostSource.choices,
        default=PostSource.MANUAL,
        db_index=True,
    )
    is_published = models.BooleanField(default=True, db_index=True)
    is_pinned = models.BooleanField(
        default=False,
        help_text="Pinned posts appear first in channel listing.",
    )

    # --- Timestamps ---
    created_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        help_text="When this record was created in our DB.",
    )
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(
        null=True,
        blank=True,
        db_index=True,
        help_text="When the post went live (can differ from created_at for scheduled posts).",
    )

    class Meta:
        db_table = "posts"
        verbose_name = "Post"
        verbose_name_plural = "Posts"
        ordering = ["-created_at"]
        indexes = [
            # Most common query: published posts for a channel, newest first
            models.Index(
                fields=["channel", "is_published", "-created_at"],
                name="idx_post_channel_published",
            ),
            # Bot deduplication lookup
            models.Index(
                fields=["channel", "telegram_message_id"],
                name="idx_post_tg_message",
            ),
            # Analytics: top posts by views
            models.Index(
                fields=["-views_count"],
                name="idx_post_views_count",
            ),
            # Filter by type within a channel
            models.Index(
                fields=["channel", "type"],
                name="idx_post_channel_type",
            ),
        ]
        constraints = [
            # A Telegram message can only be synced once per channel.
            # Prevents duplicate posts from webhook retries.
            models.UniqueConstraint(
                fields=["channel", "telegram_message_id"],
                condition=models.Q(telegram_message_id__isnull=False),
                name="uq_channel_telegram_message",
            )
        ]

    def __str__(self):
        return f"[{self.type}] {self.title or self.id} — {self.channel.slug}"


# apps/posts/models.py — PostMedia class

class PostMedia(models.Model):
    """
    Additional media files for CAROUSEL type posts.
    A Carousel post has one Post record + multiple PostMedia records.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="carousel_items",
    )
    # ← BU FIELD QO'SHILDI: avval umuman yo'q edi
    file = models.FileField(
        upload_to="posts/carousel/%Y/%m/%d/",
        blank=True,
        null=True,
        help_text=(
            "Populated by Celery after Telegram download. "
            "Null until media_tasks.process_carousel_item_media completes."
        ),
    )
    thumbnail = models.ImageField(
        upload_to="posts/carousel/thumbs/%Y/%m/%d/",
        blank=True,
        null=True,
    )
    order = models.PositiveSmallIntegerField(
        default=0,
        help_text="Display order within the carousel.",
    )
    telegram_file_id = models.CharField(max_length=256, blank=True)

    class Meta:
        db_table = "post_media"
        ordering = ["order"]
        indexes = [
            models.Index(fields=["post", "order"], name="idx_postmedia_post_order"),
        ]

    def __str__(self):
        return f"Media #{self.order} for post {self.post_id}"