# Generated by Django 4.2.11 on 2026-04-15 14:47

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID. Never expose sequential IDs in APIs.', primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(db_index=True, help_text="Telegram's own user ID. Immutable. Used for all bot interactions.", unique=True)),
                ('username', models.CharField(blank=True, db_index=True, help_text='Telegram @username. Optional — not all users have one.', max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('phone_number', models.CharField(blank=True, help_text='E.164 format preferred. Populated via bot contact share.', max_length=20)),
                ('profile_photo', models.URLField(blank=True, help_text='Telegram CDN URL. Refresh periodically — Telegram URLs expire.')),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'indexes': [models.Index(fields=['telegram_id'], name='idx_user_telegram_id'), models.Index(fields=['username'], name='idx_user_username')],
            },
        ),
    ]
