# Generated by Django 4.2.11 on 2026-05-14 17:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_id', models.CharField(db_index=True, help_text='Hashed user or session ID. Not a raw IP.', max_length=64)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='posts.post')),
            ],
            options={
                'verbose_name': 'Post View',
                'verbose_name_plural': 'Post Views',
                'db_table': 'post_views',
                'indexes': [models.Index(fields=['post', 'viewed_at'], name='idx_view_post_time'), models.Index(fields=['visitor_id', 'post'], name='idx_view_visitor_post')],
            },
        ),
        migrations.CreateModel(
            name='DailyChannelStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('post_count', models.PositiveIntegerField(default=0, help_text='Number of posts published on this date.')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='channels.channel')),
            ],
            options={
                'verbose_name': 'Daily Channel Stats',
                'verbose_name_plural': 'Daily Channel Stats',
                'db_table': 'daily_channel_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['channel', 'date'], name='idx_daily_stats_channel_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailychannelstats',
            constraint=models.UniqueConstraint(fields=('channel', 'date'), name='uq_channel_daily_stats'),
        ),
    ]
