# Generated by Django 4.2.11 on 2026-04-15 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(help_text='Auto-generated from name. Used in public URLs.', max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='channels/avatars/%Y/%m/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='channels/banners/%Y/%m/')),
                ('telegram_channel_id', models.BigIntegerField(blank=True, db_index=True, help_text="Telegram's numeric channel ID (e.g. -1001234567890). Set when bot is added as admin. Used to route incoming posts.", null=True, unique=True)),
                ('telegram_channel_username', models.CharField(blank=True, help_text='Public @username of the channel, if it has one.', max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Manually verified channels get a badge.')),
                ('subscriber_count', models.PositiveIntegerField(default=0, help_text='Cached from Telegram. Refreshed by periodic Celery task.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'db_table': 'channels',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='idx_channel_slug'), models.Index(fields=['owner', 'is_active'], name='idx_channel_owner_active'), models.Index(fields=['telegram_channel_id'], name='idx_channel_tg_id')],
            },
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_channel_id__isnull', False)), fields=('owner', 'telegram_channel_id'), name='uq_owner_telegram_channel'),
        ),
    ]
