# Generated by Django 4.2.11 on 2026-05-14 17:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('reel', 'Reel'), ('carousel', 'Carousel')], db_index=True, default='text', max_length=16)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('content', models.TextField(blank=True)),
                ('media_file', models.FileField(blank=True, help_text='Primary media asset. Stored on S3 in production.', null=True, upload_to='posts/media/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Auto-generated by Celery task for video/reel types.', null=True, upload_to='posts/thumbnails/%Y/%m/%d/')),
                ('telegram_message_id', models.BigIntegerField(blank=True, db_index=True, help_text='Original Telegram message ID. Used for deduplication and deep-link back to source.', null=True)),
                ('telegram_file_id', models.CharField(blank=True, help_text="Telegram's file_id for re-downloading media. Cheaper than storing the raw file URL.", max_length=256)),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Flushed from Redis counters by Celery batch task.', validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(choices=[('bot', 'Bot'), ('channel', 'Channel Sync'), ('manual', 'Manual')], db_index=True, default='manual', max_length=16)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned posts appear first in channel listing.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created in our DB.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='When the post went live (can differ from created_at for scheduled posts).', null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='channels.channel')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, help_text='Populated by Celery after Telegram download. Null until media_tasks.process_carousel_item_media completes.', null=True, upload_to='posts/carousel/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='posts/carousel/thumbs/%Y/%m/%d/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within the carousel.')),
                ('telegram_file_id', models.CharField(blank=True, max_length=256)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_items', to='posts.post')),
            ],
            options={
                'db_table': 'post_media',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['post', 'order'], name='idx_postmedia_post_order')],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['channel', 'is_published', '-created_at'], name='idx_post_channel_published'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['channel', 'telegram_message_id'], name='idx_post_tg_message'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-views_count'], name='idx_post_views_count'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['channel', 'type'], name='idx_post_channel_type'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_message_id__isnull', False)), fields=('channel', 'telegram_message_id'), name='uq_channel_telegram_message'),
        ),
    ]
